version: "3"

services:
  app:
    image: cooler/dev
    build:
      context: .
      target: development-environment
      args:
        # must be the same in server/build.sbt
        appName: "cooler"
        # must be the same in server/build.sbt
        appVersion: "1.0.0"
        # must be the same in server/build.sbt
        scalaVersion: "3.3.1"
    container_name: dev-backend
    ports:
      - "5000:5000"
    command: /bin/sh -c "while sleep 1000; do :; done"
  mongodb:
    image: mongo:6-jammy
    container_name: dev-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - cooler_db:/data/db
    command: mongod
    ports:
      - "27017:27017"
volumes:
  cooler_db:
    external: true
