version: "3"

services:
  mongodb:
    image: mongo:6-jammy
    restart: unless-stopped
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - cooler_db:/data/db
    command: mongod
    ports:
      - "27017:27017"
volumes:
  cooler_db:
    external: true
