services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - "$PWD/data/:/docker-entrypoint-initdb.d/"
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod
