services:
  mongodb:
    image: mongo
    container_name: db_dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - "/data/db"
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod
