services:
  app:
    build: .
    ports:
      - "5000:5000"
    command: java -jar cooler-server-assembly-0.1.0-SNAPSHOT.jar
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - "/data/db"
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod
