services:
  app:
    build:
      context: .
      args:
        APP_NAME: ${APP_NAME}
        APP_VERSION: ${APP_VERSION}
    container_name: cooler_app
    ports:
      - "5000:5000"
    command: java -jar /opt/app/${APP_NAME}-assembly-${APP_VERSION}.jar
  mongodb:
    image: mongo
    container_name: cooler_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - "/data/db"
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod
